name: Upload report to Portal
runs:
  using: composite
  steps:
    - name: curl
      shell:
      run: |
        curl -s -D - --insecure -X POST "${{ secrets.PORTAL_URL }}/api/v1/scan/import/" \
          -H "accept: application/json" \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Token ${{ secrets.SEC_PORTAL_KEY }}"  \
          -F "file=@${{ inputs.FILE_NAME }}" \
          -F "scanner_name=${{ inputs.SCAN_TYPE }}" \
          -F "product_name=$DOJO_PROJECT_NAME" \
          -F "product_type=$DOJO_PROJECT_TYPE" |
