name: Scanners
on:
  workflow_call:
    inputs:
      repo_for_scan:
        required: true
        type: string

# env:
#   repo_for_scan: 
#   required: true    
           
jobs:
  trivy:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: darialeskovets/test
          path: ./test
          ref: main
          #token: ${{ secrets.GITHUB_CUSTOM_TOKEN }}
          #token: ${{ env.SECURITY_TOKEN }}
          #token: ${{ secrets.GITHUB_TOKEN }}
          #lfs: true
          #token: ${{ secrets.SECURITY_WORKFLOW_GITHUB_TOKEN }}
          
#       - name: sfsd
#         run: |
#             sudo chmod -R 777 /home/runner/work/security-vulnerable-app-example/security-vulnerable-app-example
#             pwd 
#             ls -la
#             ls -la ./
#             ls -la test
#             ls -la test/.github/actions/upload
      - name: check var
        run: echo ${{ inputs.repo_for_scan }}
      
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
          repository: ${{ inputs.repo_for_scan }}

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          
      - name: Upload
        uses: ./test/.github/actions/upload
#          with:
#           DD_URL: ${{ secrets.DD_URL }}
#           DD_TOKEN: ${{ secrets.DD_TOKEN }}
#           DD_ENGAGEMENT_ID: ${{ env.DD_ENGAGEMENT_ID }}
#           FILE_NAME: "trivy-results.json"
#           SCAN_TYPE: "Trivy Scan"
