name: Scanners
on:
  workflow_call:
           
jobs:
  trivy:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - name: sfsd
        run: |
            sudo chmod -R 777 /home/runner/work/security-vulnerable-app-example/security-vulnerable-app-example
            pwd 
            ls -la
            ls -la ./
        
      - uses: actions/checkout@v3
        with:
          repository: darialeskovets/test
          path: ./test
          ref: main
          #token: ${{ secrets.GITHUB_CUSTOM_TOKEN }}
          #token: ${{ env.SECURITY_TOKEN }}
          #token: ${{ secrets.GITHUB_TOKEN }}
          #lfs: true
          #token: ${{ secrets.SECURITY_WORKFLOW_GITHUB_TOKEN }}
          
      - name: Upload
        uses: ./test/.github/actions/upload
#          with:
#           DD_URL: ${{ secrets.DD_URL }}
#           DD_TOKEN: ${{ secrets.DD_TOKEN }}
#           DD_ENGAGEMENT_ID: ${{ env.DD_ENGAGEMENT_ID }}
#           FILE_NAME: "trivy-results.json"
#           SCAN_TYPE: "Trivy Scan"
