name: Scanners
on:
  workflow_call:
    inputs:
      repo_for_scan:
        required: true
        type: string
jobs:
  trivy:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: darialeskovets/security-actions
          path: ./security-actions
          ref: main
      
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
          repository: ${{ inputs.repo_for_scan }}

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - uses: actions/checkout@v3
        with:
          repository: darialeskovets/security-actions
          path: ./security-actions
          ref: main

      # - name: export vars
      #   run: |  
      #     echo "REPORT_FILE=trivy-results.json" >> $GITHUB_OUTPUT
      #     echo "SCAN_TYPE=Trivy Scan" >> $GITHUB_OUTPUT
          
      - name: Upload
        uses: ./security-actions/.github/actions/upload
        with:
          FILE_NAME: "trivy-results.json"
          SCAN_TYPE: "Trivy Scan"
          PORTAL_URL: ${{ secrets.PORTAL_URL }}
          SEC_PORTAL_KEY: ${{ secrets.SEC_PORTAL_KEY }}
